config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "profile", to: "pages#profile"
    resources :garages do
      resources :reservations, only: [:new, :edit, :create, :update]
    end
    resources :reservations, only: [:index, :destroy, :show]# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garage.rb
class Garage < ApplicationRecord
  belongs_to :user
  has_many :reservation, dependent: :destroy
  validates :title, :description, :address, :phone_number, :dimensions, :price_per_day, presence: true
  validates :title, :address, uniqueness: true
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

    include PgSearch::Model
  pg_search_scope :search_by_title_and_address,
    against: [ :title, :address ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :garage
  validates :start_at, :finish_at, :price, :reservation_status, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :garages, dependent: :destroy
  has_many :reservations
  has_one_attached :photo
  validates :first_name, :last_name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/garages_controller.rb
class GaragesController < ApplicationController
  before_action :set_garage, only: %i(show edit update destroy)

  def index
    # @garages = current_user.garage
    @garages = Garage.where(user: current_user)
  end

  def show
    @reservation = Reservation.new
    @markers =
      [{
        lat: @garage.latitude,
        lng: @garage.longitude,
        infoWindow: render_to_string(partial: "shared/info_window", locals: { garage: @garage })
      }]
  end

  def new
    @garage = Garage.new
  end

  def create
    @garage = Garage.new(garage_params)
    @garage.user = current_user
    if @garage.save
      redirect_to garage_path(@garage)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @garage.update(garage_params)
    redirect_to garage_path(@garage)
  end

  def destroy
    @garage.destroy
    redirect_to garages_path
  end

  private

  def garage_params
    params.require(:garage).permit(%i(title description address availability phone_number dimensions price_per_day price_per_hour photo))
  end

  def set_garage
    @garage = Garage.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    if params[:query].present?
      @garages = Garage.search_by_title_and_address(params[:query])
    else
      @garages = Garage.all
    end
  end
  
  def profile
    @reservations = Reservation.where(user: current_user)
    @garages = Garage.where(user: current_user)
  end
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i(show edit update destroy)

  def index
    @reservations = Reservation.where(user: current_user)
  end

  def show
  end

  def new
    @garage = Garage.find(params[:garage_id])
    @reservation = Reservation.new
  end

  def create
    @garage = Garage.find(params[:garage_id])
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    @reservation.garage = @garage
    @reservation.price = (((@reservation.finish_at - @reservation.start_at)/3600)/24)*@garage.price_per_day
    @reservation.reservation_status = true
    @reservation.save!
    redirect_to reservations_path
  end

  def edit
  end

  def update
    @reservation.update(reservation_params)
    redirect_to reservation_path(@reservation)
  end

  def destroy
    @reservation.destroy
    redirect_to reservations_path
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_at, :finish_at, :price, :reservation_status, :garage_id)
  end

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/garages/edit.html.erb
<%= render 'shared/form_edit_garage' %>

app/views/garages/index.html.erb
<div class="container mt-3">
<h1 class="textito text-center">Tus garages</h1>
<% if @garages.empty? %>
  <div >
    <h3 class="textito text-center mt-3"> No hay garages disponibles </h3>
  </div>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
        <th>Garage</th>
        <th>Direccion</th>
        <th>Dimensiones</th>
        <th>Precio</th>
      </tr>
    </thead>
  <tbody>
    <% @garages.each do |garage| %>
    <tr>
      <% if garage.photo.attached? %>
        <td> <%= cl_image_tag garage.photo.key, height: 80, width: 100, crop: :fill, class: "img-fluid" %></td>
      <% else %>
         <td><%= cl_image_tag "nodisponible", height: 80, width: 100, crop: :fill, class: "img-fluid" %></td>
      <% end %>
      <td><%= link_to "#{garage.title}", garage_path(garage.id) %></td>
      <td><%= garage.address %></td>
      <td> <%= garage.dimensions %></td>
      <td><%= garage.price_per_day %></td>
      <td> <%= link_to "Eliminar", garage_path(garage.id), method: :delete, class: "btn btn-danger"  %></td>
     <% end %>
    </tr>
  </tbody>
  </table>
<% end %>
  <div class="d-flex justify-content-center mt-4">
    <%= link_to "Volver", root_path, class: "btn btn-outline-dark mr-2" %>
  </div>
</div>
<div class="fixed-bottom">
<%= render 'shared/footer' %>
</div>

app/views/garages/new.html.erb
<%= render 'shared/form_garage_new' %>

app/views/garages/show.html.erb
<%= render 'shared/showwgarage' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rentalgarage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    

    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@200&display=swap" rel="stylesheet">
    
    
    
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
   <%= render 'shared/navbar' %>
   <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>
<%= render 'shared/garagescard' %>

app/views/pages/profile.html.erb
<div class="container">

  <div class="card-profile mt-4 shadow-lg p-3 mb-5 bg-white rounded">
    <img src="https://avatars1.githubusercontent.com/u/61606998?s=460&u=082a27d6296fd919af71818b5754d987140f71b4&v=4" />
   <div class="card-profile-infos">
      <h4 class=""> <strong> Nombre :</strong> <%= current_user.first_name%> </h3>
      <h4 class=""><strong> Apellido :</strong>  <%=current_user.last_name  %> </h3>
      <h6 class=""><strong> Email :</strong>  <%=current_user.email  %> </h6>
      <%= link_to "Editar Perfil", edit_user_registration_path , class:"btn btn-outline-dark ml-1" %>
    </div>
  </div>

  
  <div>
  <div class="container mt-3 ">
<h1 class="vanaranja textito text-center ">Tus reservas</h1>
<% if @reservations.empty? %>
  <div >
    <h3 class="textito text-center mt-3"> No hay reservas disponibles </h3>
  </div>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
        <th>Garage</th>
        <th>Direccion</th>
        <th>Desde</th>
        <th>Hasta</th>
        <th>Precio</th>
      </tr>
    </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
    <tr>
     <% if reservation.garage.photo.attached? %>
        <td> <%= cl_image_tag reservation.garage.photo.key, height: 80, width: 100, crop: :fill, class: "img-fluid" %></td>
      <% else %>
         <td><%= cl_image_tag "nodisponible", height: 80, width: 100, crop: :fill, class: "img-fluid" %></td>
      <% end %>
      <td><%= link_to "#{reservation.garage.title}", garage_path(reservation.garage.id) %></td>
      <td><%= reservation.garage.address %></td>
      <td> <%= reservation.start_at %></td>
      <td><%= reservation.finish_at %></td>
      <td><%= reservation.price %></td>
      <td> <%= link_to "Cancelar", reservation_path(reservation.id), method: :delete, class: "btn btn-danger"  %></td>
     <% end %>
    </tr>
  </tbody>
  </table>
  <% end %> 
  <div class="d-flex justify-content-center mt-4">
  </div>
  </div>



  <div>
    <div class="container mt-3">
<h1 class="vanaranja textito text-center">Tus garages</h1>
<% if @garages.empty? %>
  <div >
    <h3 class="textito text-center mt-3"> No hay garages disponibles </h3>
  </div>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
        <th>Garage</th>
        <th>Direccion</th>
        <th>Dimensiones</th>
        <th>Precio</th>
    </thead>
  <tbody>
    <% @garages.each do |garage| %>
    <tr>
      <% if garage.photo.attached? %>
        <td> <%= cl_image_tag garage.photo.key, height: 80, width: 100, crop: :fill, class: "img-fluid" %></td>
      <% else %>
         <td><%= cl_image_tag "nodisponible", height: 80, width: 100, crop: :fill, class: "img-fluid" %></td>
      <% end %>
      <td><%= link_to "#{garage.title}", garage_path(garage.id) %></td>
      <td><%= garage.address %></td>
      <td> <%= garage.dimensions %></td>
      <td><%= garage.price_per_day %></td>
      <td > <%= link_to "Eliminar", garage_path(garage.id), method: :delete, class: "eliminar btn btn-danger align-content-end"  %></td>

     <% end %>
    </tr>
  </tbody>
  </table>
<% end %>
  <div class="d-flex justify-content-center mt-4">
    <%= link_to "Volver", root_path, class: "btn btn-outline-dark mr-2" %>
  </div>
</div>
  
  </div>

  </div>
</div>

app/views/reservations/index.html.erb
<div class="container mt-3">
<h1 class="textito text-center">Tus reservas</h1>
<% if @reservations.empty? %>
  <div >
    <h3 class="textito text-center mt-3"> No hay reservas disponibles </h3>
  </div>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
        <th>Garage</th>
        <th>Direccion</th>
        <th>Desde</th>
        <th>Hasta</th>
        <th>Precio</th>
      </tr>
    </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
    <tr>
     <% if reservation.garage.photo.attached? %>
        <td> <%= cl_image_tag reservation.garage.photo.key, height: 80, width: 100, crop: :fill, class: "img-fluid" %></td>
      <% else %>
         <td><%= cl_image_tag "nodisponible", height: 80, width: 100, crop: :fill, class: "img-fluid" %></td>
      <% end %>
      <td><%= link_to "#{reservation.garage.title}", garage_path(reservation.garage.id) %></td>
      <td><%= reservation.garage.address %></td>
      <td> <%= reservation.start_at %></td>
      <td><%= reservation.finish_at %></td>
      <td><%= reservation.price %></td>
      <td> <%= link_to "Cancelar", reservation_path(reservation.id), method: :delete, class: "btn btn-danger"  %></td>
     <% end %>
    </tr>
  </tbody>
  </table>
<% end %>
  <div class="d-flex justify-content-center mt-4">
    <%= link_to "Volver", root_path, class: "btn btn-outline-dark mr-2" %>
  </div>
</div>
<div class="fixed-bottom">
<%= render 'shared/footer' %>
</div>

app/views/reservations/new.html.erb
<div class="container">
<h1 class="text-center">Nueva Reserva</h1>
  <div class="card">
  <div id="formulario" class="container text-center">
    <%= simple_form_for [ @garage, @reservation ] do |f| %>
      <p>Cochera: <%= @garage.title %></p>
      <p>Direccion: <%= @garage.address %></p>
      <small>Description: <%= @garage.description %></small>
      <p>Precio: $<%= @garage.price_per_day %> / dia</p>
      <%= f.input :start_at, label:"Fecha y hora de comienzo:",required:false %>
      <%= f.input :finish_at, label:"Fecha y hora fin:", required:false %>
      <%= f.submit "Alquilar", class:"btn btn-dark" %>
    <% end %>
  </div>
  <%= link_to "Volver", root_path, class: "btn btn-outline-dark mr-2" %>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn.lowgif.com/full/9425340509733885-parking-fail-gifs-get-the-best-gif-on-giphy.gif);">
  <div class="container">
    <h1 id="tituloBanner" class="text-center">  GarBnb </h1>
    <p class="text-center">Consegui estacionamiento en todos los barrios con el mejor precio y la mayor seguridad</p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Hecho con <i class="fas fa-heart"></i> por Platon
  </div>
</div>

app/views/shared/_form_edit_garage.html.erb
<div class="container">
  <div class="log-card mt-4">
    <h3 class="text-center">Actualice su garage</h3>
    <div class="form">
      <div class="form-inputs">
        <%= simple_form_for @garage do |f| %>
          <%= f.input :title, label:"Titulo:", required: false %>
          <%= f.input :phone_number, label:"Teléfono:", required: false %>
          <%= f.input :address, label:"Dirección:", required: false %>
          <%= f.input :dimensions, label:"Dimensiones:", required: false %>
          <%= f.input :price_per_day, label:"Precio por dia:", required: false %>
          <%= f.input :description, label:"Descripción:", required: false %>
          <%= f.input :photo, as: :file, label:"Actualice imágen:", required: false %>
          <%= f.button :submit, value:"Actualizar", class: "btn btn-outline-dark"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_form_garage_new.html.erb
<div class="container">
  <div id="form_garage_new"class="log-card mt-3">
    <h3 id="tit_new_garage"class="textito text-center">Nuevo Garage</h3>
    <div class="form">
      <div class="form-inputs">
        <%= simple_form_for @garage do |f| %>
          <%= f.input :title, label:"Título:", required: false %>
          <%= f.input :phone_number, label:"Teléfono:", required: false %>
          <%= f.input :address, label:"Dirección:", required: false %>
          <%= f.input :dimensions, label:"Dimensiones:", required: false %>
          <%= f.input :price_per_day, label:"Precio por día:", required: false %>
          <%= f.input :description, label:"Descripción:", required: false %>
          <%= f.input :photo, as: :file, label:"Agregá una imagen:", required: false %>
          <%= f.button :submit, label:"Agregar", class: "btn btn-outline-dark" %> 
          <%= link_to "Restablecer", "", class: "btn btn-outline-warning"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_garagescard.html.erb
<div class="container">
  <div class="row justify-content-center">
      <% @garages.each do |garage| %>
        <div class="col-4 p-3">
          <div id="cardcita" class="shadow-lg rounded p-3 mt-2 bg-white h-100 text-center d-flex flex-column justify-content-between"> 
            <div class="card-img-top">
              <% if garage.photo.attached? %>
              <%= cl_image_tag garage.photo.key, height: 550, width: 750, crop: :fill, class: "fotita img-fluid" %>
              <% else %>
               <%= cl_image_tag "nodisponible", height: 550, width: 550, crop: :fill, class: "img-fluid" %>
              <% end %>
            </div>
            <div>
              <div id="description_card" class="">
                <h4 id="titulito"><%= garage.title %></h4>
                <div class="description">
                  <small><%= garage.description %></small>
                </div>
                <p> $ <%= garage.price_per_day %>/  Dia</p>
              </div> <%# ALQUILAR %>
              <div id="buttons_card" class="">  
                <% if current_user%>
                  <%=link_to "Alquilar", garage_path(garage), class:"btn btn-dark mr-1" %>
                  <%# VER MAS %>
                  <% end  %>
                  <%=link_to "Ver Mas", garage_path(garage), class:"btn btn-warning " %>
              </div>
            </div>
          </div>  
        </div>
      <% end %>     
  </div>
</div>
<%= render 'shared/footer' %>

app/views/shared/_info_window.html.erb
<h5 class="text-center"><%= garage.title %></h5>
<p><%= garage.address %></p>

app/views/shared/_map.html.erb
<div id="map"
  style="width: 100%; height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/shared/_modal_reservation_confirmation.html.erb
<div class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <%= link_to "/", class: "navbar-brand" do %>
    <i class="fas fa-car"></i>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<!--   <form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
    <div id="barrita" class="search-form-control form-group d-flex m-3">
      <input class="border border-dark  form-control string requirer" placeholder="Buscar garages por zona" type="text" name="" id="" />
      <button name="button" type="submit" class="btn btn-flat"> <i class="fas fa-search"></i></button>
    </div>
  </form>  -->
    <!-- [...] -->
  <div class="buscador_navbar">
    <%= form_tag root_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "search-form-control form-group",
        placeholder: "Buscar un garage"
      %>
      <div class="lupa_navbar">
        <button name="button" type="submit" class="btn btn-flat" >
          <%= submit_tag "", class: "btn btn-flat" %>
          <i class="fas fa-search"></i>
        </button>
      </div>
    <% end %>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active"><%= link_to "Mis Garages", garages_path, class: "dropdown-item" %> </li>
        <li class="nav-item active"><%= link_to "Mis Reservas", reservations_path, class: "dropdown-item" %> </li>
        <li class="nav-item active"><%= link_to "Agregar Garage", new_garage_path, class: "dropdown-item" %> </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://avatars1.githubusercontent.com/u/61606998?s=460&u=082a27d6296fd919af71818b5754d987140f71b4&v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Perfil", "/profile", class: "dropdown-item" %>
            <%= link_to "Configuracion", edit_user_registration_path , class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
          <%= link_to "Iniciar Sesion", new_user_session_path, class: "btn btn-outline-dark mr-2" %>
          <%= link_to "Registrate", new_user_registration_path, class: "btn btn-outline-warning" %>

        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_showwgarage.html.erb
  <% if @garage.photo.attached? %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%=cl_image_path @garage.photo.key %>)">
  <% else %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://thumbs.dreamstime.com/b/limpie-el-garage-19656222.jpg)">
  <% end %>
  <h1 id="tituloo"> <%= @garage.title  %> </h1>
</div>

  <div id="arriba" class="cards mx-4">

      <div id="foto"class="card-category col align-self-center ">
        <% if @garage.photo.attached? %>
          <%= cl_image_tag @garage.photo.key, height: 300, width: 450, crop: :fill, class: "fotitolinda img-fluid"%>
        <% else %>
          <%= cl_image_tag "nodisponible", height: 300, width: 300, crop: :fill, class: "img-fluid" %>
        <% end %>
      </div>
    
      <div id="medio" class="card-category">
        <h1 class="text-center mt-3"><%= @garage.title %></h1>
        <p class="text-center"><%= @garage.description %></p>
        <p class="text-center"><strong> Dirección: </strong><%= @garage.address %></p>
        <p class="text-center"><strong> Teléfono: </strong><%= @garage.phone_number %></p>
        <p class="text-center"><strong> Dimensiones: </strong><%= @garage.dimensions %></p>
        <p class="text-center"><strong> Precio: </strong> $ <%= @garage.price_per_day %> / Dia <p>
        <% if current_user.id == @garage.user_id%>
          <div class="text-center">
            <%=link_to "Actualizar", edit_garage_path(@garage), class:"btn btn-dark mr-1 btn-lg " %>
          </div>
        <% else %>
          <div class="text-center">
            <button type="button" id="boton-show-alquilar" class="btn btn-warning btn-lg" data-toggle="modal" data-target="#staticBackdrop">
              Alquilar
            </button>
          </div>
        <% end  %>

      </div>
      <div id="derecha">
        <%= render 'shared/map' %>
      </div>
  </div>

<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h5 class="modal-title" id="staticBackdropLabel">Nueva Reserva</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
 <div id="formulario" class="container text-center">
    <%= simple_form_for [ @garage, @reservation ] do |f| %>
      <p>Cochera: <%= @garage.title %></p>
      <p>Direccion: <%= @garage.address %></p>
      <small>Description: <%= @garage.description %></small>
      <p>Precio: $<%= @garage.price_per_day %> / dia</p>
      <%= f.input :start_at, as: :date, order: [:day, :month, :year], label:"Fecha y hora de comienzo:",required:false %>
      <%= f.input :finish_at, as: :date, order: [:day, :month, :year], label:"Fecha y hora fin:", required:false %>
      <%= f.submit "Alquilar", class:"btn btn-dark align-center" %>
    <% end %>
  </div>
      </div>
    </div>
  </div>
</div>
<div class="div_vacio_show"></div>
<div class="fixed-bottom">
<%= render 'shared/footer' %>
</div>